# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/kilin_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_power = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_power.setGeometry(QtCore.QRect(10, 10, 200, 220))
        self.groupBox_power.setObjectName("groupBox_power")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_power)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 160, 144))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_emergency_stop = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_emergency_stop.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_emergency_stop.setFont(font)
        self.btn_emergency_stop.setStyleSheet("QPushButton {\n"
"    background-color: firebrick;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 15px;\n"
"    border: 2px solid darkred;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkred;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_emergency_stop.setCheckable(False)
        self.btn_emergency_stop.setObjectName("btn_emergency_stop")
        self.verticalLayout_4.addWidget(self.btn_emergency_stop)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.led_digital = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.led_digital.setMinimumSize(QtCore.QSize(20, 20))
        self.led_digital.setMaximumSize(QtCore.QSize(20, 20))
        self.led_digital.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;\n"
"min-width: 20px;\n"
"min-height: 20px;\n"
"")
        self.led_digital.setText("")
        self.led_digital.setObjectName("led_digital")
        self.horizontalLayout_2.addWidget(self.led_digital)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.led_signal = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.led_signal.setMinimumSize(QtCore.QSize(20, 20))
        self.led_signal.setMaximumSize(QtCore.QSize(20, 20))
        self.led_signal.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;\n"
"min-width: 20px;\n"
"min-height: 20px;\n"
"")
        self.led_signal.setText("")
        self.led_signal.setObjectName("led_signal")
        self.horizontalLayout_4.addWidget(self.led_signal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.led_power = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.led_power.setMinimumSize(QtCore.QSize(20, 20))
        self.led_power.setMaximumSize(QtCore.QSize(20, 20))
        self.led_power.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;\n"
"min-width: 20px;\n"
"min-height: 20px;\n"
"")
        self.led_power.setText("")
        self.led_power.setObjectName("led_power")
        self.horizontalLayout.addWidget(self.led_power)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_digital = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_digital.setObjectName("btn_digital")
        self.verticalLayout.addWidget(self.btn_digital)
        self.btn_signal = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_signal.setObjectName("btn_signal")
        self.verticalLayout.addWidget(self.btn_signal)
        self.btn_power = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_power.setObjectName("btn_power")
        self.verticalLayout.addWidget(self.btn_power)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_power)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_voltage = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_voltage.setMinimumSize(QtCore.QSize(65, 21))
        self.label_voltage.setMaximumSize(QtCore.QSize(65, 21))
        self.label_voltage.setObjectName("label_voltage")
        self.horizontalLayout_5.addWidget(self.label_voltage)
        self.text_voltage_display = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.text_voltage_display.setMinimumSize(QtCore.QSize(70, 21))
        self.text_voltage_display.setMaximumSize(QtCore.QSize(100, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_voltage_display.setFont(font)
        self.text_voltage_display.setStyleSheet("")
        self.text_voltage_display.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_voltage_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_voltage_display.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.text_voltage_display.setObjectName("text_voltage_display")
        self.horizontalLayout_5.addWidget(self.text_voltage_display)
        self.groupBox_hotkey = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hotkey.setGeometry(QtCore.QRect(10, 240, 200, 191))
        self.groupBox_hotkey.setObjectName("groupBox_hotkey")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_hotkey)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 30, 101, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_input = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_input.setObjectName("comboBox_input")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_input)
        self.btn_send = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_send.setObjectName("btn_send")
        self.verticalLayout_6.addWidget(self.btn_send)
        self.btn_rest = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rest.setObjectName("btn_rest")
        self.verticalLayout_6.addWidget(self.btn_rest)
        self.btn_setzero = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_setzero.setObjectName("btn_setzero")
        self.verticalLayout_6.addWidget(self.btn_setzero)
        self.btn_brake = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_brake.setObjectName("btn_brake")
        self.verticalLayout_6.addWidget(self.btn_brake)
        self.groupBox_log = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_log.setGeometry(QtCore.QRect(10, 450, 200, 141))
        self.groupBox_log.setObjectName("groupBox_log")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_log)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 170, 91))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_filename = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_filename.setMinimumSize(QtCore.QSize(165, 0))
        self.label_filename.setMaximumSize(QtCore.QSize(165, 16777215))
        self.label_filename.setObjectName("label_filename")
        self.verticalLayout_8.addWidget(self.label_filename)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.verticalLayout_8.addWidget(self.lineEdit_filename)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_log = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_log.setObjectName("btn_log")
        self.horizontalLayout_8.addWidget(self.btn_log)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.groupBox_script = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_script.setGeometry(QtCore.QRect(10, 600, 200, 141))
        self.groupBox_script.setObjectName("groupBox_script")
        self.btn_trigger = QtWidgets.QPushButton(self.groupBox_script)
        self.btn_trigger.setGeometry(QtCore.QRect(30, 60, 139, 31))
        self.btn_trigger.setStyleSheet("QPushButton {\n"
"    background-color: #444444;\n"
"    color: #BBBBBB;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btn_trigger.setObjectName("btn_trigger")
        self.groupBox_module_c = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_module_c.setGeometry(QtCore.QRect(220, 380, 520, 370))
        self.groupBox_module_c.setMinimumSize(QtCore.QSize(520, 370))
        self.groupBox_module_c.setMaximumSize(QtCore.QSize(520, 370))
        self.groupBox_module_c.setObjectName("groupBox_module_c")
        self.groupBox_module_d = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_module_d.setGeometry(QtCore.QRect(750, 380, 520, 400))
        self.groupBox_module_d.setMinimumSize(QtCore.QSize(520, 400))
        self.groupBox_module_d.setMaximumSize(QtCore.QSize(520, 400))
        self.groupBox_module_d.setObjectName("groupBox_module_d")
        self.groupBox_module_a = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_module_a.setGeometry(QtCore.QRect(220, 10, 520, 370))
        self.groupBox_module_a.setMinimumSize(QtCore.QSize(520, 370))
        self.groupBox_module_a.setMaximumSize(QtCore.QSize(520, 370))
        self.groupBox_module_a.setObjectName("groupBox_module_a")
        self.groupBox_module_b = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_module_b.setGeometry(QtCore.QRect(750, 10, 520, 370))
        self.groupBox_module_b.setMinimumSize(QtCore.QSize(520, 370))
        self.groupBox_module_b.setMaximumSize(QtCore.QSize(520, 370))
        self.groupBox_module_b.setObjectName("groupBox_module_b")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "Emergency stop"))
        self.groupBox_power.setTitle(_translate("MainWindow", "Power"))
        self.btn_emergency_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_digital.setText(_translate("MainWindow", "Digital"))
        self.btn_signal.setText(_translate("MainWindow", "Signal"))
        self.btn_power.setText(_translate("MainWindow", "Power"))
        self.label_voltage.setText(_translate("MainWindow", "Voltage:"))
        self.groupBox_hotkey.setTitle(_translate("MainWindow", "HotKey"))
        self.comboBox_input.setItemText(0, _translate("MainWindow", "UI"))
        self.comboBox_input.setItemText(1, _translate("MainWindow", "Manual"))
        self.btn_send.setText(_translate("MainWindow", "Send"))
        self.btn_rest.setText(_translate("MainWindow", "Rest"))
        self.btn_setzero.setText(_translate("MainWindow", "Set Zero"))
        self.btn_brake.setText(_translate("MainWindow", "Brake"))
        self.groupBox_log.setTitle(_translate("MainWindow", "Log"))
        self.label_filename.setText(_translate("MainWindow", "FileName:"))
        self.btn_log.setText(_translate("MainWindow", "Logging"))
        self.groupBox_script.setTitle(_translate("MainWindow", "Other"))
        self.btn_trigger.setText(_translate("MainWindow", "TRIGGER OFF"))
        self.groupBox_module_c.setTitle(_translate("MainWindow", "Module C"))
        self.groupBox_module_d.setTitle(_translate("MainWindow", "Module D"))
        self.groupBox_module_a.setTitle(_translate("MainWindow", "Module A"))
        self.groupBox_module_b.setTitle(_translate("MainWindow", "Module B"))
