#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>
#include "rclcpp/rclcpp.hpp"
#include "kilin_msgs/msg/leg_cmd.hpp"
#include "kilin_msgs/msg/motor_cmd_stamped.hpp"
#include "kilin_msgs/msg/motor_state_stamped.hpp"
namespace fs=std::filesystem; constexpr int REST=0,POS=4,SPEED=5,TORQUE=6,BRAKE=7; constexpr double D2R=M_PI/180.; constexpr std::array<const char*,4> N{"A","B","C","D"};
enum class Phase {WAIT, STARTUP_MOVE, ZERO_HOLD, STATIC_RELEASE, MOVE, HOLD, FINAL_HOLD, RECOVERY_REST, RECOVERY_MOVE, DONE, ABORT};
class Runner final:public rclcpp::Node{
 public: Runner():Node("kilin_hip_characterization"){
  armed_=declare_parameter<bool>("armed",false); topic_=declare_parameter<std::string>("command_topic","/kilin/hip_characterization/command_preview"); state_topic_=declare_parameter<std::string>("state_topic","/motor/state"); run_dir_=declare_parameter<std::string>("run_dir",""); name_=declare_parameter<std::string>("strategy_name","phase_a_two_state_baseline"); version_=declare_parameter<std::string>("strategy_version","1.0.0"); hz_=declare_parameter<double>("publish_rate_hz",100); reps_=declare_parameter<int>("repetitions",3); modules_=declare_parameter<std::vector<std::string>>("active_modules",{"A","B"}); mode_=declare_parameter<std::string>("motion_mode","two_state_cycle"); state_a_deg_=declare_parameter<double>("state_a_deg",0); state_b_deg_=declare_parameter<double>("state_b_deg",45); seq_param_=declare_parameter<std::vector<double>>("outward_sequence_deg",{0,45,0}); zero_tol_=declare_parameter<double>("startup_state_tolerance_deg",declare_parameter<double>("startup_zero_tolerance_deg",3)); speed_=declare_parameter<double>("hip_speed_rad_s",0);
  kp_=declare_parameter<double>("kp",350);ki_=declare_parameter<double>("ki",0);kd_=declare_parameter<double>("kd",5); const double oldff=declare_parameter<double>("hip_ff_torque_nm",0); ff_out_=declare_parameter<double>("hip_ff_outward_direct",oldff);ff_in_=declare_parameter<double>("hip_ff_inward_direct",oldff);ff_static_out_=declare_parameter<double>("hip_ff_static_outward_direct",0);ff_static_in_=declare_parameter<double>("hip_ff_static_inward_direct",0);ff_limit_=declare_parameter<double>("max_abs_hip_ff_torque_nm",200); ff_rate_min_=declare_parameter<double>("ff_motion_min_rate_rad_s",.03);ff_enable_=declare_parameter<double>("ff_error_enable_rad",.010);ff_disable_=declare_parameter<double>("ff_error_disable_rad",.004);
  zero_hold_=declare_parameter<double>("start_zero_hold_s",2); static_s_=declare_parameter<double>("static_release_ramp_s",1); static_fraction_=declare_parameter<double>("static_release_fraction",.15); hold_s_=declare_parameter<double>("segment_hold_s",1); final_hold_=declare_parameter<double>("final_zero_hold_s",3); fallback_s_=declare_parameter<double>("fallback_segment_s",2); startup_speed_=declare_parameter<double>("startup_move_speed_rad_s",.1); recovery_deg_=declare_parameter<double>("recovery_position_deg",0); recovery_speed_=declare_parameter<double>("recovery_move_speed_rad_s",.1); recovery_rest_s_=declare_parameter<double>("recovery_rest_s",1); state_age_=declare_parameter<double>("max_state_age_s",.1);error_limit_=declare_parameter<double>("max_abs_hip_error_rad",.35);hip_torque_limit_=declare_parameter<double>("max_abs_hip_torque_nm",4);hub_torque_limit_=declare_parameter<double>("max_abs_hub_torque_nm",2);
  wheel_=declare_parameter<std::string>("wheel_mode","rest"); const double oldwo=declare_parameter<double>("wheel_torque_extend_nm",0),oldwi=declare_parameter<double>("wheel_torque_contract_nm",0); wheel_out_=declare_parameter<double>("wheel_torque_outward_nm",oldwo);wheel_in_=declare_parameter<double>("wheel_torque_inward_nm",oldwi);L_=declare_parameter<double>("hip_to_wheel_m",.260);R_=declare_parameter<double>("wheel_radius_m",.051); valid(); wheel_code_=wheelCode(wheel_);
  pub_=create_publisher<kilin_msgs::msg::MotorCmdStamped>(topic_,10);sub_=create_subscription<kilin_msgs::msg::MotorStateStamped>(state_topic_,rclcpp::QoS(20).best_effort(),std::bind(&Runner::state,this,std::placeholders::_1));timer_=create_wall_timer(std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::duration<double>(1/hz_)),std::bind(&Runner::tick,this)); RCLCPP_WARN(get_logger(),"Strategy %s is %s. Real actuation requires armed:=true and command_topic:=/motor/command.",version_.c_str(),armed_?"ARMED":"DISARMED"); }
 ~Runner()override{if(armed_&&running())stop();}
 private: struct J{double p=NAN,v=NAN,t=NAN,d=NAN;int e=0;}; std::array<J,4> hip_{},hub_{};
 void valid(){if(reps_<1||hz_<=0||speed_<0||zero_tol_<0||static_s_<=0||static_fraction_<0||static_fraction_>=1||fallback_s_<=0||ff_disable_<0||ff_enable_<ff_disable_||ff_limit_<=0||L_<=0||R_<=0)throw std::runtime_error("invalid campaign parameters");if(armed_&&run_dir_.empty())throw std::runtime_error("armed campaigns require run_dir");if(mode_!="two_state_cycle"&&mode_!="zero_cycle"&&mode_!="outward_sequence")throw std::runtime_error("motion_mode must be two_state_cycle or outward_sequence");for(auto&m:modules_)if(std::none_of(N.begin(),N.end(),[&](auto x){return m==x;}))throw std::runtime_error("unknown active module");for(auto x:{ff_out_,ff_in_,ff_static_out_,ff_static_in_})if(std::abs(x)>ff_limit_)throw std::runtime_error("hip FF exceeds limit");if(std::abs(wheel_out_)>hub_torque_limit_||std::abs(wheel_in_)>hub_torque_limit_)throw std::runtime_error("wheel torque exceeds limit");}
 static int wheelCode(const std::string&s){if(s=="rest")return REST;if(s=="position_hold")return POS;if(s=="speed")return SPEED;if(s=="torque")return TORQUE;if(s=="brake")return BRAKE;throw std::runtime_error("invalid wheel_mode");} static double cl(double x){return std::clamp(x,0.,1.);}static double sm(double x){x=cl(x);return x*x*(3-2*x);} static double rpm10(double x){return x*600/(2*M_PI);} bool active(size_t i)const{return std::find(modules_.begin(),modules_.end(),N[i])!=modules_.end();}double outsign(size_t i)const{return i<2?-1:1;}double actual(size_t i)const{return hip_[i].p+hip_[i].d;} bool fresh()const{return got_&&(now()-last_).seconds()<=state_age_;}bool running()const{return phase_!=Phase::WAIT&&phase_!=Phase::DONE&&phase_!=Phase::ABORT;}
 void state(const kilin_msgs::msg::MotorStateStamped::SharedPtr m){const std::array<kilin_msgs::msg::LegState,4> a{m->module_a,m->module_b,m->module_c,m->module_d};for(size_t i=0;i<4;i++){hip_[i]={a[i].hip.position,a[i].hip.velocity,a[i].hip.torque,a[i].hip.position_diff,a[i].hip.error_code};hub_[i]={a[i].hub.position,a[i].hub.velocity,a[i].hub.torque,a[i].hub.position_diff,a[i].hub.error_code};}last_=now();got_=true;}
 void setup(){seq_=(mode_=="two_state_cycle"||mode_=="zero_cycle")?std::vector<double>{state_a_deg_,state_b_deg_,state_a_deg_}:seq_param_;if(seq_.size()<2)throw std::runtime_error("sequence requires at least two states");for(auto q:seq_)if(q<0)throw std::runtime_error("sequence is outward magnitudes only");if(std::abs(seq_.back()-seq_.front())>1e-9)seq_.push_back(seq_.front());for(size_t i=0;i<4;i++){if(!std::isfinite(actual(i)))throw std::runtime_error("non-finite hip state");hub0_[i]=hub_[i].p;move_start_[i]=actual(i);cmd_[i]=actual(i);ff_on_[i]=false;}seg_=0;trial_=0;phase_=Phase::STARTUP_MOVE;t0_=now();openLog();}
 void openLog(){if(run_dir_.empty())return;fs::create_directories(run_dir_);trace_.open(fs::path(run_dir_)/"command_state_trace.csv");trace_<<"time_s,strategy_name,strategy_version,trial,phase,segment,module,hip_cmd_motor_rad,hip_cmd_actual_rad,hip_cmd_rate_rad_s,hip_ff_direct,hip_motor_rad,angle_diff_rad,hip_actual_rad,hip_vel_rad_s,hip_torque,hip_error_code,hub_mode,hub_cmd_value,hub_pos_rad,hub_vel_rad_s,hub_torque\n";std::ofstream o(fs::path(run_dir_)/"trial_manifest.yaml");o<<"strategy_name: "<<name_<<"\nstrategy_version: "<<version_<<"\nangle_convention: actual_hip_angle_rad = motor_position + position_diff\ncommand_topic: "<<topic_<<"\narmed: "<<(armed_?"true":"false")<<"\nmotion_mode: "<<mode_<<"\nsequence_outward_deg: [";for(size_t i=0;i<seq_.size();i++)o<<(i?", ":"")<<seq_[i];o<<"]\nrepetitions: "<<reps_<<"\nwheel_mode: "<<wheel_<<"\nkp: "<<kp_<<"\nki: "<<ki_<<"\nkd: "<<kd_<<"\nhip_ff_outward_direct: "<<ff_out_<<"\nhip_ff_inward_direct: "<<ff_in_<<"\nhip_ff_static_outward_direct: "<<ff_static_out_<<"\nhip_ff_static_inward_direct: "<<ff_static_in_<<"\n";}
 double a(size_t i,bool end)const{return active(i)?outsign(i)*seq_[seg_+(end?1:0)]*D2R:0;}double d(size_t i)const{return a(i,true)-a(i,false);}double recovery(size_t i)const{return active(i)?outsign(i)*recovery_deg_*D2R:0;}bool stat()const{return seg_==0&&seq_[0]==0&&seq_[1]>0;}double duration()const{double z=0;for(size_t i=0;i<4;i++)z=std::max(z,std::abs(d(i)));if(stat())z*=1-static_fraction_;return speed_>0?z/speed_:fallback_s_;}double moveDuration(bool recover)const{double z=0;for(size_t i=0;i<4;i++)z=std::max(z,std::abs((recover?recovery(i):a(i,false))-move_start_[i]));double v=recover?recovery_speed_:startup_speed_;return v>0?z/v:fallback_s_;}double elapsed()const{return(now()-t0_).seconds();}double frac()const{if(phase_==Phase::STARTUP_MOVE||phase_==Phase::RECOVERY_MOVE)return sm(elapsed()/moveDuration(phase_==Phase::RECOVERY_MOVE));if(phase_==Phase::STATIC_RELEASE)return static_fraction_*sm(elapsed()/static_s_);if(phase_==Phase::MOVE)return stat()?static_fraction_+(1-static_fraction_)*cl(elapsed()/duration()):cl(elapsed()/duration());if(phase_==Phase::HOLD)return 1;return 0;}double rate(size_t i)const{if(!active(i))return 0;if(phase_==Phase::STARTUP_MOVE||phase_==Phase::RECOVERY_MOVE){double u=cl(elapsed()/moveDuration(phase_==Phase::RECOVERY_MOVE));return ((phase_==Phase::RECOVERY_MOVE?recovery(i):a(i,false))-move_start_[i])*6*u*(1-u)/moveDuration(phase_==Phase::RECOVERY_MOVE);}if(phase_==Phase::MOVE)return d(i)*(stat()?1-static_fraction_:1)/duration();if(phase_==Phase::STATIC_RELEASE){double u=cl(elapsed()/static_s_);return d(i)*static_fraction_*6*u*(1-u)/static_s_;}return 0;}
 bool unsafe()const{for(size_t i=0;i<4;i++)if(!std::isfinite(actual(i))||!std::isfinite(hip_[i].t)||hip_[i].e||std::abs(hip_[i].t)>hip_torque_limit_||std::abs(actual(i)-cmd_[i])>error_limit_)return true;return false;}
 void reportFault()const{for(size_t i=0;i<4;i++)if(hip_[i].e)RCLCPP_ERROR(get_logger(),"Fault name: hip_motor_reported_fault; module=%s error_code=%d",N[i],hip_[i].e);}
 double ff(size_t i,double r){if(!active(i)||(phase_!=Phase::STATIC_RELEASE&&(phase_!=Phase::MOVE||std::abs(r)<ff_rate_min_))){ff_on_[i]=false;return 0;}double e=cmd_[i]-actual(i);if(r*e<=0)ff_on_[i]=false;else if(!ff_on_[i]&&std::abs(e)>=ff_enable_)ff_on_[i]=true;else if(ff_on_[i]&&std::abs(e)<=ff_disable_)ff_on_[i]=false;if(!ff_on_[i])return 0;bool outward=r*outsign(i)>0;double mag=phase_==Phase::STATIC_RELEASE?(outward?ff_static_out_:ff_static_in_):(outward?ff_out_:ff_in_);return std::clamp(std::copysign(std::abs(mag),r),-ff_limit_,ff_limit_);}
 kilin_msgs::msg::MotorCmd hipCmd(size_t i){kilin_msgs::msg::MotorCmd c; if(phase_==Phase::STARTUP_MOVE)cmd_[i]=move_start_[i]+frac()*(a(i,false)-move_start_[i]);else if(phase_==Phase::RECOVERY_MOVE)cmd_[i]=move_start_[i]+frac()*(recovery(i)-move_start_[i]);else cmd_[i]=(phase_==Phase::STATIC_RELEASE||phase_==Phase::MOVE||phase_==Phase::HOLD)?a(i,false)+frac()*d(i):a(i,false);c.motor_mode=POS;c.position=cmd_[i]-hip_[i].d;c.kp=kp_;c.ki=ki_;c.kd=kd_;c.torque=ff(i,rate(i));return c;}kilin_msgs::msg::MotorCmd wheelCmd(size_t i,double r)const{kilin_msgs::msg::MotorCmd c;if(phase_==Phase::STARTUP_MOVE||phase_==Phase::RECOVERY_MOVE||phase_==Phase::RECOVERY_REST){c.motor_mode=REST;return c;}c.motor_mode=wheel_code_;double wr=-L_*std::cos(cmd_[i])*r/R_;if(wheel_code_==POS)c.position=hub0_[i];if(wheel_code_==SPEED)c.velocity=rpm10(wr);if(wheel_code_==TORQUE){bool outward=r*outsign(i)>0;double mag=(phase_==Phase::STATIC_RELEASE||phase_==Phase::MOVE)?(outward?wheel_out_:wheel_in_):0;c.torque=std::clamp(std::copysign(std::abs(mag),wr==0?1:wr),-hub_torque_limit_,hub_torque_limit_);}return c;}
 void hdr(kilin_msgs::msg::MotorCmdStamped&m){auto t=now();m.header.seq=serial_++;m.header.time.sec=(int)t.seconds();m.header.time.nanosec=t.nanoseconds()%1000000000LL;m.header.frame_id="kilin_hip_characterization";}void stop(){kilin_msgs::msg::MotorCmdStamped m;hdr(m);kilin_msgs::msg::LegCmd x;x.hip.motor_mode=REST;x.steering.motor_mode=REST;x.hub.motor_mode=BRAKE;m.module_a=x;m.module_b=x;m.module_c=x;m.module_d=x;pub_->publish(m);}
 void publish(){kilin_msgs::msg::MotorCmdStamped m;hdr(m);std::array<kilin_msgs::msg::LegCmd,4> x;for(size_t i=0;i<4;i++){x[i].hip=hipCmd(i);x[i].steering.motor_mode=POS;x[i].steering.position=0;x[i].hub=wheelCmd(i,rate(i));}m.module_a=x[0];m.module_b=x[1];m.module_c=x[2];m.module_d=x[3];pub_->publish(m);if(trace_)for(size_t i=0;i<4;i++){auto&h=x[i].hub;double hv=wheel_code_==POS?h.position:wheel_code_==SPEED?h.velocity:h.torque;trace_<<now().seconds()<<','<<name_<<','<<version_<<','<<trial_+1<<','<<(int)phase_<<','<<seg_<<','<<N[i]<<','<<x[i].hip.position<<','<<cmd_[i]<<','<<rate(i)<<','<<x[i].hip.torque<<','<<hip_[i].p<<','<<hip_[i].d<<','<<actual(i)<<','<<hip_[i].v<<','<<hip_[i].t<<','<<hip_[i].e<<','<<h.motor_mode<<','<<hv<<','<<hub_[i].p<<','<<hub_[i].v<<','<<hub_[i].t<<'\n';}}
 bool expired()const{return phase_==Phase::STARTUP_MOVE?elapsed()>=moveDuration(false):phase_==Phase::ZERO_HOLD?elapsed()>=zero_hold_:phase_==Phase::STATIC_RELEASE?elapsed()>=static_s_:phase_==Phase::MOVE?elapsed()>=duration():phase_==Phase::HOLD?elapsed()>=hold_s_:phase_==Phase::FINAL_HOLD?elapsed()>=final_hold_:phase_==Phase::RECOVERY_REST?elapsed()>=recovery_rest_s_:phase_==Phase::RECOVERY_MOVE?elapsed()>=moveDuration(true):false;}void advance(){t0_=now();if(phase_==Phase::STARTUP_MOVE)phase_=Phase::ZERO_HOLD;else if(phase_==Phase::ZERO_HOLD)phase_=stat()?Phase::STATIC_RELEASE:Phase::MOVE;else if(phase_==Phase::STATIC_RELEASE)phase_=Phase::MOVE;else if(phase_==Phase::MOVE)phase_=Phase::HOLD;else if(phase_==Phase::HOLD){if(++seg_+1<seq_.size())phase_=Phase::MOVE;else phase_=Phase::FINAL_HOLD;}else if(phase_==Phase::FINAL_HOLD){if(++trial_>=reps_)phase_=Phase::RECOVERY_REST;else{seg_=0;ff_on_.fill(false);phase_=Phase::ZERO_HOLD;}}else if(phase_==Phase::RECOVERY_REST){for(size_t i=0;i<4;i++)move_start_[i]=actual(i);phase_=Phase::RECOVERY_MOVE;}else if(phase_==Phase::RECOVERY_MOVE)phase_=Phase::DONE;}
 void tick(){if(!armed_)return;if(!fresh()){if(running()){phase_=Phase::ABORT;stop();RCLCPP_ERROR(get_logger(),"Campaign aborted: /motor/state stale.");rclcpp::shutdown();}return;}if(phase_==Phase::WAIT){try{setup();RCLCPP_INFO(get_logger(),"Startup move begins; trial 1/%d.",reps_);}catch(const std::exception&e){phase_=Phase::ABORT;RCLCPP_ERROR(get_logger(),"Campaign refused: %s",e.what());rclcpp::shutdown();}return;}if(!running())return;if(unsafe()){reportFault();phase_=Phase::ABORT;stop();RCLCPP_ERROR(get_logger(),"Campaign aborted: motor or tracking safety limit.");rclcpp::shutdown();return;}if(phase_==Phase::RECOVERY_REST)stop();else publish();if(expired()){advance();if(phase_==Phase::DONE){stop();RCLCPP_INFO(get_logger(),"Campaign complete.");rclcpp::shutdown();}}}
 bool armed_{false},got_{false};std::string topic_,state_topic_,run_dir_,name_,version_,mode_,wheel_;double hz_{100},state_a_deg_{0},state_b_deg_{45},zero_tol_{3},speed_{0},kp_{350},ki_{0},kd_{5},ff_out_{0},ff_in_{0},ff_static_out_{0},ff_static_in_{0},ff_limit_{200},ff_rate_min_{.03},ff_enable_{.01},ff_disable_{.004},zero_hold_{2},static_s_{1},static_fraction_{.15},hold_s_{1},final_hold_{3},fallback_s_{2},startup_speed_{.1},recovery_deg_{0},recovery_speed_{.1},recovery_rest_s_{1},state_age_{.1},error_limit_{.35},hip_torque_limit_{4},hub_torque_limit_{2},wheel_out_{0},wheel_in_{0},L_{.260},R_{.051};int reps_{3},trial_{0},wheel_code_{REST};uint32_t serial_{0};size_t seg_{0};std::vector<std::string> modules_;std::vector<double>seq_param_,seq_;std::array<double,4>cmd_{},hub0_{},move_start_{};std::array<bool,4>ff_on_{};Phase phase_{Phase::WAIT};rclcpp::Time t0_{0,0,RCL_ROS_TIME},last_{0,0,RCL_ROS_TIME};std::ofstream trace_;rclcpp::Publisher<kilin_msgs::msg::MotorCmdStamped>::SharedPtr pub_;rclcpp::Subscription<kilin_msgs::msg::MotorStateStamped>::SharedPtr sub_;rclcpp::TimerBase::SharedPtr timer_;
};int main(int argc,char**argv){rclcpp::init(argc,argv);rclcpp::spin(std::make_shared<Runner>());rclcpp::shutdown();return 0;}
