<?xml version="1.0"?>
<package format="3">
  <name>kilin_csv_control</name>
  <version>0.0.0</version>
  <description>CSV-based motor command controller for Kilin robot.</description>
  <maintainer email="ian20030201@gmail.com">ian920201</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>kilin_msgs</depend>

  <build_depend>libgpiod-dev</build_depend>
  <exec_depend>libgpiod2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
